import type { AdminPerfume } from "./components/admin-perfumes-table";

export const ADMIN_PERFUMES: AdminPerfume[] = [
  {
    id: "p1",
    name: "9PM",
    designer: "Bang Olufsen",
    image: "https://i.ibb.co/hFK9vN9C/9pm.png",
    type: "ARABIC",
    price: 114,
    stock: 10,
    status: "Activo",
  },
  {
    id: "p2",
    name: "Aventus",
    designer: "Creed",
    image: "https://i.ibb.co/yBFvP0jT/aventus.png",
    type: "DESIGNER",
    price: 95,
    stock: 24,
    status: "Activo",
  },
  {
    id: "p3",
    name: "Acqua di Giò",
    designer: "Giorgio Armani",
    image: "https://i.ibb.co/qLrc9K9N/acqua-di-gi-eau-de-parfum-intense.png",
    type: "DESIGNER",
    price: 130,
    stock: 5,
    status: "Agotado",
  },
  {
    id: "p4",
    name: "Eros",
    designer: "Rayhaan",
    image: "https://i.ibb.co/7NXVHmcL/eros.png",
    type: "ARABIC",
    price: 92,
    stock: 0,
    status: "Inactivo",
  },
  {
    id: "p5",
    name: "Sauvage",
    designer: "Dior",
    image: "https://i.ibb.co/Vpgb8pPF/sauvage.png",
    type: "DESIGNER",
    price: 105,
    stock: 18,
    status: "Activo",
  },
];